services:
  db:
    image: postgres:15-alpine
    container_name: study_xp_tracker_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: study_xp_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: study_xp_tracker_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: study_xp_tracker_azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azuritedata:/data

volumes:
  pgdata:
  redisdata:
  azuritedata:
