import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const translations = {
  vi: {
    // auth / login / register
    login_title: "Study XP Tracker",
    login_subtitle: "Đăng nhập để tiếp tục cày cuốc học tập và thăng cấp!",
    email: "Email",
    password: "Mật khẩu",
    login_btn: "Đăng nhập",
    logging_in: "Đang đăng nhập...",
    no_account: "Chưa có tài khoản?",
    create_account: "Tạo tài khoản mới",
    register_title: "Đăng ký tài khoản",
    register_subtitle: "Bắt đầu hành trình theo dõi học tập và thăng cấp XP!",
    display_name: "Tên hiển thị",
    confirm_password: "Xác nhận mật khẩu",
    register_btn: "Đăng ký",
    already_have_account: "Đã có tài khoản?",
    login_now: "Đăng nhập ngay",
    passwords_dont_match: "Mật khẩu xác nhận không khớp. Vui lòng kiểm tra lại.",
    register_failed: "Đăng ký thất bại. Vui lòng thử lại.",
    login_failed: "Đăng nhập thất bại. Vui lòng kiểm tra lại thông tin.",
    loading_account: "Đang tải tài khoản...",

    // validation error messages
    error_email_required: "Vui lòng nhập địa chỉ email.",
    error_email_invalid: "Email không đúng định dạng. (ví dụ: ten@vi-du.com)",
    error_password_required: "Vui lòng nhập mật khẩu.",
    error_password_min_length: "Mật khẩu phải có ít nhất 6 ký tự.",
    error_confirm_password_required: "Vui lòng xác nhận lại mật khẩu.",
    error_confirm_password_mismatch: "Mật khẩu xác nhận không khớp. Vui lòng kiểm tra lại.",
    error_display_name_required: "Vui lòng nhập tên hiển thị.",
    error_display_name_length: "Tên hiển thị phải từ 2 đến 50 ký tự.",
    error_otp_required: "Vui lòng nhập đầy đủ 4 chữ số mã OTP.",
    error_otp_expired: "Mã OTP đã hết hạn (quá 5 phút). Vui lòng bấm 'Gửi lại mã' hoặc thực hiện đăng ký lại.",

    // friendly error messages (mapped from API error codes)
    error_invalid_credentials: "Email hoặc mật khẩu không đúng. Vui lòng kiểm tra lại.",
    error_account_not_found: "Không tìm thấy tài khoản với email này.",
    error_email_already_exists: "Email này đã được sử dụng. Vui lòng dùng email khác hoặc đăng nhập.",
    error_invalid_input: "Thông tin nhập vào không hợp lệ. Vui lòng kiểm tra lại các trường.",
    error_session_already_active: "Bạn đang có một phiên học chưa kết thúc.",
    error_session_not_found: "Không tìm thấy phiên học này.",
    error_bad_request: "Yêu cầu không hợp lệ. Vui lòng kiểm tra lại thông tin.",
    error_unauthorized: "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.",
    error_forbidden: "Bạn không có quyền thực hiện hành động này.",
    error_not_found: "Không tìm thấy tài nguyên yêu cầu.",
    error_too_many_requests: "Bạn đã thử quá nhiều lần. Vui lòng chờ một lúc rồi thử lại.",
    error_server: "Máy chủ đang gặp sự cố. Vui lòng thử lại sau.",
    error_unknown: "Đã xảy ra lỗi không xác định. Vui lòng thử lại.",


    // dashboard layout & navbar
    logout: "Đăng xuất",
    theme_light: "Chế độ sáng",
    theme_dark: "Chế độ tối",
    language: "Ngôn ngữ",
    nav_messages: "Tin nhắn",
    nav_messages_title: "Cửa sổ nhắn tin",
    nav_friends: "Bạn bè",
    nav_friends_title: "Danh sách bạn bè",
    customize_dashboard: "Tùy chỉnh giao diện",
    dashboard_customizer_title: "Cài Đặt Màn Hình Dashboard",
    dashboard_customizer_desc: "Bật/tắt các ô tiện ích bạn muốn hiển thị trên màn hình học tập.",
    reset_default: "Hiện lại tất cả",
    reset_order: "Đặt lại thứ tự",
    save_and_close: "Lưu & Đóng",
    drag_to_reorder: "Kéo để đổi vị trí",
    widget_hidden_badge: "Đang ẩn",
    widget_xpBar_name: "Cấp độ & Điểm XP",
    widget_xpBar_desc: "Hiển thị cấp độ hiện tại, điểm kinh nghiệm và tiến trình lên cấp",
    widget_studyTimer_name: "Đồng hồ bấm giờ học",
    widget_studyTimer_desc: "Bộ tính giờ tập trung học tập và nhận thưởng điểm XP",
    widget_manualSession_name: "Ghi chép buổi học",
    widget_manualSession_desc: "Tự lưu thời gian học khi bạn học sách vở offline hoặc quên bấm giờ",
    widget_onlineUsers_name: "Bạn học đang online",
    widget_onlineUsers_desc: "Xem danh sách bạn bè và cộng đồng cũng đang tập trung học",
    widget_countdown_name: "Đếm ngược ngày thi",
    widget_countdown_desc: "Theo dõi số ngày đếm ngược đến các kỳ thi quan trọng",
    widget_sessionHistory_name: "Nhật ký học tập",
    widget_sessionHistory_desc: "Xem lại danh sách các buổi học bạn đã hoàn thành gần đây",
    all_widgets_hidden: "Bạn đã ẩn tất cả tiện ích",
    all_widgets_hidden_desc: "Bấm vào nút dưới đây để mở lại cài đặt và chọn tiện ích muốn hiển thị",

    // xp bar
    level: "Cấp",
    study_progress: "Tiến Trình Học Tập",
    total_xp: "Tổng XP tích lũy",
    xp_to_next: "cần thiết để lên cấp",
    session_active: "Mức XP Ước Tính (Đang học)",
    session_saved: "Mức XP Hiện Tại",

    // study timer
    timer_title: "Đồng Hồ Học Tập",
    select_subject: "Chọn môn học",
    timer_active_desc: "Bạn đang tập trung học",
    timer_stopped_desc: "Đồng hồ đang dừng",
    timer_placeholder: "Tự do / Khác",
    btn_start: "Bắt đầu tập trung",
    btn_pause: "Tạm dừng",
    btn_resume: "Tiếp tục",
    btn_stop: "Kết thúc & Nhận XP",
    session_completed: "Học tập hoàn thành",
    minutes: "phút",
    timer_start_error: "Không thể bắt đầu học tập.",
    timer_stop_error: "Không thể dừng học tập.",
    timer_counting: "Đang đếm giờ...",
    timer_ready: "Sẵn sàng",
    timer_input_placeholder: "Môn học / Chủ đề (ví dụ: Toán, Lập trình...)",
    timer_btn_start: "Bắt đầu học ngay",

    // study methods i18n
    select_method_title: "Phương pháp học tập",
    method_free: "Tự do (Stopwatch)",
    method_pomodoro_25_5: "Pomodoro 25/5",
    method_pomodoro_50_10: "Pomodoro 50/10",
    method_rule_52_17: "Quy tắc 52/17",
    method_deep_work_90_20: "Deep Work 90/20",
    method_active_recall_30_10: "Active Recall 30/10",
    method_free_desc: "Đếm tiến thời gian học tự do",
    method_pomodoro_25_5_desc: "25 phút học + 5 phút nghỉ",
    method_pomodoro_50_10_desc: "50 phút học + 10 phút nghỉ",
    method_rule_52_17_desc: "52 phút học + 17 phút nghỉ",
    method_deep_work_90_20_desc: "90 phút đào sâu + 20 phút nghỉ",
    method_active_recall_30_10_desc: "30 phút tự học + 10 phút rà soát",
    break_time_title: "Giờ Nghỉ Thư Giãn ☕",
    break_time_desc: "Hãy thả lỏng mắt và thư giãn trước chu kỳ mới!",
    bonus_xp_tag: "+15% XP Thưởng",
    camera_presence_guard: "Xác nhận có mặt (Camera AI)",
    camera_presence_guard_on: "AI Camera Guard: ĐANG BẬT (+15% XP)",
    camera_presence_guard_off: "AI Camera Guard: ĐANG TẮT",
    status_present: "Đang có mặt",
    status_absent: "Cảnh báo: Vắng mặt",
    camera_access_denied: "Không thể truy cập camera",
    camera_loading: "Đang khởi tạo AI...",
    auto_pause_title: "Tự động Tạm dừng Phiên học",
    auto_pause_desc: "Đã tự động tạm dừng do không phát hiện bạn trước camera trong 5 phút.",
    btn_resume_study: "Tôi đã quay lại (Tiếp tục học)",

    // manual session
    manual_title: "Tự Ghi Nhận Buổi Học",
    subject: "Môn học",
    duration: "Thời gian học (phút)",
    btn_log: "Ghi nhận buổi học",
    log_success: "Đã ghi nhận buổi học thành công!",
    log_error: "Ghi nhận thất bại. Vui lòng thử lại.",
    hour: "giờ",
    minute: "phút",
    second: "giây",
    goal_log_error: "Không thể tự động ghi nhận buổi học",
    goal_duration_error: "Thời lượng mục tiêu phải lớn hơn 0 giây.",
    goal_countdown_title: "Đặt Mục Tiêu Đếm Ngược",
    goal_subject_placeholder: "Toán, Lý, Lập trình...",
    goal_duration_label: "Thời gian học mục tiêu",
    goal_btn_add: "Thêm mục tiêu mới",
    goal_list_title: "Mục Tiêu Đã Đặt Ra",
    goal_no_goals: "Chưa có mục tiêu học tập nào được đặt.",
    goal_status_completed: "Đã hoàn thành",
    goal_status_running: "Đang chạy",
    goal_status_paused: "Tạm dừng",
    goal_set_label: "Đặt ra:",
    goal_btn_start: "Bắt đầu",
    goal_btn_delete: "Xóa mục tiêu",
    goal_completed_title: "Hoàn Thành Mục Tiêu! 🎉",
    goal_completed_desc: "Chúc mừng bạn đã hoàn thành xuất sắc mục tiêu học tập môn",
    goal_completed_in: "trong",
    goal_btn_ok: "Tuyệt vời!",

    // countdown keys
    countdown_widget_title: "Đếm Ngược Mục Tiêu",
    countdown_subtitle: "Theo dõi mốc thời gian thi & sự kiện quan trọng",
    countdown_select_preset: "Chọn kỳ thi / sự kiện mẫu",
    countdown_manage_btn: "Quản lý đếm ngược",
    countdown_days: "ngày",
    countdown_hours: "giờ",
    countdown_minutes: "phút",
    countdown_seconds: "giây",
    countdown_official_badge: "Lịch thi chính thức",
    countdown_estimated_badge: "Lịch dự kiến (Auto-Sync)",
    countdown_add_new: "Tạo bộ đếm tùy chỉnh",
    countdown_event_title: "Tên kỳ thi / Sự kiện",
    countdown_target_date: "Ngày giờ diễn ra",
    countdown_note: "Ghi chú mục tiêu",
    countdown_email_notify: "Nhận thông báo qua Email khi sắp tới mốc thi",
    countdown_pin: "Ghim lên Dashboard",
    countdown_unpin: "Bỏ ghim",
    countdown_delete: "Xóa đếm ngược",
    countdown_save: "Lưu thông tin",
    countdown_empty: "Chưa có bộ đếm ngược nào.",
    countdown_tab_presets: "Sự kiện & Kỳ thi cộng đồng",
    countdown_tab_custom: "Bộ đếm của bạn",
    countdown_presets_desc: "Khám phá và theo dõi các kỳ thi chính thức & sự kiện do cộng đồng học tập đăng tải.",
    countdown_trackers_count: "người đang theo dõi",
    countdown_trackers_count_suffix: "người cùng theo dõi",
    countdown_share_community: "🌐 Chia sẻ với cộng đồng (Công khai cho mọi người cùng theo dõi)",
    countdown_created_by: "Đóng góp bởi",
    countdown_community_badge: "Cộng đồng",
    countdown_search_placeholder: "Tìm kiếm kỳ thi, sự kiện...",
    countdown_btn_track: "Theo dõi",

    countdown_btn_tracking: "Đang theo dõi",
    countdown_btn_untrack: "Hủy theo dõi",
    countdown_pinned_badge: "Đang ghim",
    countdown_quote_normal: "Hãy duy trì thói quen học tập tích tiểu thành đại!",
    countdown_quote_warning: "⚡ Còn ít hơn 30 ngày! Tăng tốc luyện đề ngay nào!",
    countdown_quote_urgent: "🔥 Thời gian đếm ngược chặng cuối! Giữ vững tinh thần!",

    // preset exams i18n
    THPT_QG_2027_title: "Kỳ thi Tốt nghiệp THPT Quốc Gia 2027",
    THPT_QG_2027_desc: "Kỳ thi tốt nghiệp THPT Quốc Gia chính thức hàng năm",
    DGNL_HCMUT_2027_title: "Kỳ thi ĐGNL Bách Khoa HCMUT 2027",
    DGNL_HCMUT_2027_desc: "Kỳ thi Đánh giá năng lực Trường Đại học Bách Khoa TP.HCM",
    DGNL_VNU_HCM_2027_title: "Kỳ thi ĐGNL ĐHQG TP.HCM Đợt 1 2027",
    DGNL_VNU_HCM_2027_desc: "Kỳ thi Đánh giá năng lực Đại học Quốc gia TP.HCM",
    DGNL_HSA_VNU_HN_2027_title: "Kỳ thi HSA ĐHQG Hà Nội 2027",
    DGNL_HSA_VNU_HN_2027_desc: "Kỳ thi Đánh giá năng lực học sinh THPT của ĐHQG Hà Nội",
    TET_AM_2027_title: "Tết Nguyên Đán Đinh Mùi 2027",
    TET_AM_2027_desc: "Tết Cổ Truyền Việt Nam (Mùng 1 Tết)",



    // online users
    online_title: "Study Room",
    online_users: "Online",
    no_online_users: "No one else is online right now.",
    level_short: "Lv",
    total_xp_short: "XP",
    studying_subject: "Studying",
    status_active_idle: "Online · Idle",
    no_online_short: "No one online",

    // session history
    history_title: "Lịch Sử Học Tập",
    no_sessions: "Chưa có buổi học nào được ghi nhận.",
    delete_confirm: "Xóa buổi học này?",
    source_timer: "Bấm giờ",
    source_manual: "Nhập tay",
    chart_minutes_label: "Số phút",
    chart_title: "Thống Kê 7 Ngày Qua",
    no_sessions_subtitle: "Hãy bật đồng hồ hoặc ghi nhận buổi học để tích lũy XP!",
    filter_all: "Tất cả",
    filter_today: "Hôm nay",
    filter_7d: "7 ngày qua",
    filter_30d: "30 ngày qua",
    filter_custom: "Chọn ngày",
    filter_title: "Lọc theo thời gian:",
    no_filtered_sessions: "Không tìm thấy buổi học nào trong khoảng thời gian này.",

    // study calendar
    calendar_title: "Study Calendar",
    one_year_past: "Past Year",
    total_active_days: "Study Days",
    current_streak: "Streak",
    longest_streak: "Best Streak",
    longest_streak_year: "Best This Year",
    total_duration: "Total Time",
    days: "d",
    hours: "h",
    no_study_time: "No study time yet",
    hover_tip: "Hover cells to see session details",
    legend_less: "Less",
    legend_more: "More",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],

    // landing page
    landing_slogan: "Study Tracker - Web Theo Dõi Học Tập & Thăng Cấp XP",
    landing_sub: "Công cụ Study Tracker miễn phí giúp biến mỗi phút học tập thành điểm kinh nghiệm (XP), thăng cấp RPG, đếm giờ Pomodoro và cày cuốc cùng bạn bè trực tuyến.",
    landing_cta_get_started: "Bắt đầu cày cuốc",
    landing_cta_login: "Đăng nhập",
    landing_cta_features: "Khám phá tính năng",
    landing_mock_timer_title: "Chạy thử đồng hồ & Nhận XP",

    // member search & public profile
    search_members: "Tìm kiếm thành viên",
    search_members_placeholder: "Nhập tên hiển thị hoặc email...",
    no_members_found: "Không tìm thấy thành viên nào phù hợp.",
    view_profile: "Xem hồ sơ",
    public_profile_title: "Hồ Sơ Thành Viên",
    member_level: "Cấp độ",
    member_streak: "Chuỗi học tập",
    member_total_time: "Tổng thời gian học",
    member_total_sessions: "Tổng số buổi học",
    member_status_online: "Trực tuyến",
    member_status_offline: "Ngoại tuyến",
    member_status_studying: "Đang tập trung học",
    member_bio_title: "Mục tiêu & Giới thiệu",
    member_no_bio: "Thành viên này chưa cập nhật giới thiệu.",
    close: "Đóng",
    landing_mock_timer_desc: "Nhấn nút dưới để bắt đầu mô phỏng phiên học thực tế.",
    landing_mock_btn_start: "Bắt đầu học thử",
    landing_mock_btn_stop: "Dừng & Claim XP!",
    landing_mock_level_up: "THĂNG CẤP! 🎉",
    landing_mock_xp_gained: "Bạn đã nhận được",
    landing_mock_total_xp: "Tổng XP giả lập",
    landing_feature_title: "Các tính năng nổi bật",
    landing_feature_timer_title: "Đồng hồ Pomodoro chống gian lận",
    landing_feature_timer_desc: "Theo dõi thời gian học từng giây. Đảm bảo chống gian lận thông qua tính toán trực tiếp từ máy chủ.",
    landing_feature_rpg_title: "Cơ chế game nhập vai RPG",
    landing_feature_rpg_desc: "Công thức thăng cấp thú vị, tặng thêm 10% XP cho các buổi học tập trung chất lượng cao trên 25 phút.",
    landing_feature_coop_title: "Phòng học trực tuyến cùng bạn bè",
    landing_feature_coop_desc: "Nhìn thấy danh sách những người học trực tuyến khác cùng với trạng thái và cấp độ của họ để duy trì động lực.",
    landing_feature_heatmap_title: "Lịch học & Chuỗi ngày (Streaks)",
    landing_feature_heatmap_desc: "Lịch đóng góp giống Github và thống kê chi tiết giúp bạn theo dõi sát sao tiến độ học tập hàng tuần.",
    landing_back_to_home: "Trở về Trang chủ",
    landing_showcase_title: "Theo dõi trực quan tiến độ học tập",
    landing_showcase_desc: "Website cung cấp hệ thống lịch học (Contribution Map) giống phong cách GitHub, tự động lưu lại tất cả chuỗi ngày liên tiếp bạn học tập (Streaks). Ngoài ra còn tích hợp biểu đồ thống kê 7 ngày gần nhất sử dụng thư viện Recharts để bạn dễ dàng đánh giá sự tập trung của bản thân.",
    landing_showcase_item1: "Thống kê chi tiết số phút học mỗi ngày",
    landing_showcase_item2: "Theo dõi chuỗi ngày học hiện tại và chuỗi dài nhất để kích hoạt động lực cày cuốc",
    landing_showcase_item3: "Dễ dàng ghi nhận thủ công nếu học ngoại tuyến hoặc quên chạy đồng hồ",
    landing_showcase_btn: "Trải nghiệm ngay",
    landing_mock_streak: "Chuỗi Ngày",
    landing_mock_level: "Cấp Độ",
    landing_mock_duration: "Thời Gian Học",
    landing_mock_heatmap_title: "Lịch học đóng góp (Heatmap)",
    landing_mock_coop_title: "Đang Học Cùng Bạn",
    landing_mock_user1_subject: "Đang học Toán Giải Tích",
    landing_mock_user2_subject: "Đang học Lập Trình Java",

    // rank i18n
    global_rank: "Hạng",
    global_rank_unranked: "Chưa xếp hạng",
    global_rank_total_users: "người dùng",

    // guest mode
    guest_login: "Đăng nhập Khách",
    guest_login_btn: "Vào học ngay",
    guest_login_subtitle: "Chỉ cần nhập tên hiển thị để trải nghiệm ngay hệ thống!",
    guest_name_label: "Tên hiển thị của bạn",
    guest_name_placeholder: "Ví dụ: Khách Cần Mẫn...",
    guest_badge: "Tài khoản Khách",
    guest_overlay_title: "Tạo tài khoản để lưu lịch sử học tập",
    guest_overlay_desc: "Bạn đang dùng tài khoản khách. Đăng ký ngay để mở khóa Thống kê 7 ngày, Heatmap và lưu giữ toàn bộ dữ liệu học tập!",
    guest_register_cta: "Đăng ký lưu dữ liệu",

    // footer author info
    footer_author_title: "Thông tin tác giả",
    footer_author_name: "Tác giả",
    footer_contact_email: "Email liên hệ",
    footer_address: "Địa chỉ",
    footer_copyright: "Ứng dụng gamification hỗ trợ theo dõi thời gian học tập, thăng cấp XP và duy trì thói quen học tập hiệu quả.",

    // user profile & settings
    profile_seo_title: "Trang Cá Nhân & Cài Đặt - Study XP Tracker",
    profile_seo_desc: "Quản lý thông tin tài khoản, avatar, danh hiệu và tùy chỉnh trải nghiệm học tập.",
    back_to_dashboard: "Quay Lại Dashboard",
    profile_user_default: "Người dùng",
    profile_total_xp: "Tổng XP:",
    profile_daily_goal: "Mục tiêu ngày:",
    profile_tab_info: "Hồ Sơ Cá Nhân",
    profile_tab_security: "Bảo Mật & Mật Khẩu",
    profile_tab_titles: "Danh Hiệu RPG",
    profile_tab_preferences: "Cài Đặt Trải Nghiệm",
    profile_edit_info: "Chỉnh Sửa Thông Tin Cá Nhân",
    profile_display_name_label: "Tên Hiển Thị (Display Name):",
    profile_display_name_placeholder: "Ví dụ: Nguyễn Văn A",
    profile_daily_goal_label: "Mục Tiêu Học Tập Hàng Ngày (Phút):",
    profile_goal_30: "30 phút / ngày (Cơ bản)",
    profile_goal_60: "60 phút / ngày (Tiêu chuẩn)",
    profile_goal_90: "90 phút / ngày (Tăng tốc)",
    profile_goal_120: "120 phút / ngày (Chăm chỉ)",
    profile_goal_180: "180 phút / ngày (Siêu luyện)",
    profile_favorite_subjects_label: "Môn Học / Chủ Đề Ưu Thích:",
    profile_favorite_subjects_placeholder: "Ví dụ: Lập trình Java, Tiếng Anh, Toán Cao Cấp...",
    profile_bio_label: "Tiểu Sử / Câu Trích Dẫn Yêu Thích (Bio):",
    profile_bio_placeholder: "Chia sẻ mục tiêu học tập hoặc phương châm cá nhân...",
    profile_char_limit: "ký tự",
    profile_btn_save: "Lưu Thay Đổi",
    profile_saving: "Đang lưu...",
    profile_security_title: "Quản Lý Bảo Mật & Mật Khẩu",
    profile_google_title: "Đăng Nhập Bằng Google",
    profile_google_desc: "Tài khoản này được liên kết và đăng nhập thông qua Google OAuth2. Mật khẩu của bạn được bảo mật tuyệt đối bởi Google.",
    profile_current_password: "Mật Khẩu Hiện Tại:",
    profile_new_password: "Mật Khẩu Mới (Tối thiểu 6 ký tự):",
    profile_confirm_password: "Xác Nhận Mật Khẩu Mới:",
    profile_btn_change_password: "Đổi Mật Khẩu",
    profile_processing: "Đang xử lý...",
    profile_titles_title: "Danh Hiệu RPG Học Tập",
    profile_titles_desc: "Tăng Level học tập của bạn để mở khóa các danh hiệu độc quyền và trang bị danh hiệu hiển thị công khai!",
    profile_title_unlocked: "Đã Mở",
    profile_title_req_lvl: "Cần Lvl",
    profile_title_equipped: "Đang Trang Bị",
    profile_title_equip_btn: "Trang Bị Danh Hiệu",
    profile_preferences_title: "Cài Đặt Trải Nghiệm & Giao Diện",
    profile_theme_accent_label: "Tông Màu Nổi Bật (Theme Accent):",
    profile_accent_indigo: "Indigo (Mặc định)",
    profile_accent_emerald: "Emerald Green",
    profile_accent_rose: "Rose Red",
    profile_accent_amber: "Amber Gold",
    profile_accent_purple: "Royal Purple",
    profile_system_language_label: "Ngôn Ngữ Hệ Thống (System Language):",
    profile_sound_fx_title: "Hiệu Ứng Âm Thanh (Sound FX)",
    profile_sound_fx_desc: "Phát âm thanh chúc mừng khi hoàn thành Pomodoro hoặc Level Up.",
    profile_privacy_status_title: "Quyền riêng tư Trạng thái hoạt động",
    profile_privacy_status_desc: "Cho phép người dùng khác xem trạng thái Online & Đang học của bạn.",
    profile_privacy_everyone_title: "Công khai với tất cả người dùng",
    profile_privacy_everyone_desc: "Mọi thành viên đều nhìn thấy khi bạn online hoặc đang trong phiên học.",
    profile_privacy_friends_title: "Chỉ danh sách bạn bè",
    profile_privacy_friends_desc: "Chỉ những người dùng đã trở thành bạn bè mới thấy trạng thái online/đang học của bạn.",
    profile_privacy_nobody_title: "Ẩn với tất cả (Chế độ ẩn danh)",
    profile_privacy_nobody_desc: "Không ai nhìn thấy trạng thái online hoặc phiên học của bạn.",
    profile_message_permission_title: "Quyền nhận tin nhắn riêng (Direct Messages)",
    profile_message_permission_desc: "Thiết lập ai có thể gửi tin nhắn trực tiếp cho bạn trong hệ thống Study XP Tracker.",
    profile_msg_everyone_title: "Tất cả mọi người",
    profile_msg_everyone_desc: "Bất kỳ người dùng nào cũng có thể gửi tin nhắn cho bạn.",
    profile_msg_friends_title: "Chỉ bạn bè",
    profile_msg_friends_desc: "Chỉ những người dùng đã kết bạn mới có thể gửi tin nhắn cho bạn.",
    profile_msg_nobody_title: "Không nhận tin nhắn",
    profile_msg_nobody_desc: "Từ chối tất cả tin nhắn từ bất kỳ ai.",
    profile_theme_mode_title: "Chế độ Giao diện (Theme)",
    profile_theme_mode_desc: "Chuyển đổi giữa giao diện Sáng (Light) và Tối (Dark) cho hệ thống.",
    profile_theme_light_label: "Chế độ Sáng (Light Mode)",
    profile_theme_dark_label: "Chế độ Tối (Dark Mode)",
    profile_logout_desc: "Đăng xuất khỏi phiên làm việc hiện tại trên thiết bị này.",
    profile_btn_save_settings: "Lưu Cài Đặt",
    profile_toast_info_success: "Đã cập nhật thông tin cá nhân thành công.",
    profile_toast_avatar_success: "Đã cập nhật ảnh đại diện mới thành công.",
    profile_toast_preset_avatar_success: "Đã thay đổi Avatar thành công.",
    profile_toast_password_success: "Đã đổi mật khẩu thành công. Vui lòng ghi nhớ mật khẩu mới.",
    profile_toast_title_success: "Đã trang bị danh hiệu",

    // avatar uploader vi
    avatar_title: "Ảnh Đại Diện",
    avatar_desc: "Tải ảnh từ thiết bị của bạn hoặc chọn nhanh từ kho Avatar Hoạt Hình RPG.",
    avatar_tab_upload: "Tải Ảnh Lên",
    avatar_tab_preset: "Kho Avatar RPG",
    avatar_tab_generator: "Tạo Ngẫu Nhiên",
    avatar_drag_drop: "Kéo thả file vào đây hoặc bấm để tải lên",
    avatar_support_formats: "Hỗ trợ PNG, JPG, WEBP (nén tự động dưới 5MB)",
    avatar_btn_cancel: "Hủy Chọn",
    avatar_btn_save: "Lưu Ảnh Đại Diện",
    avatar_preset_subtitle: "Chọn 1 avatar hoạt hình phong cách RPG dưới đây:",
    avatar_gen_style: "Phong Cách (Style):",
    avatar_gen_seed: "Từ Khóa (Seed / Tên):",
    avatar_gen_btn: "Tạo Mới",
    avatar_gen_preview: "Xem trước avatar tạo ra",
    avatar_gen_use: "Chọn Avatar Này",
    avatar_cancel_tooltip: "Hủy chọn file",

    // rpg titles i18n
    "title_Tân Binh Tập Trung": "Tân Binh Tập Trung",
    "title_Học Giả Bền Bỉ": "Học Giả Bền Bỉ",
    "title_Chiến Binh Pomodoro": "Chiến Binh Pomodoro",
    "title_Bậc Thầy Tập Trung": "Bậc Thầy Tập Trung",
    "title_Đại Sứ Học Thuật": "Đại Sứ Học Thuật",
    "title_Huyền Thoại XP": "Huyền Thoại XP",
    "title_Thượng Cổ Thần Học": "Thượng Cổ Thần Học",

    "title_desc_Tân Binh Tập Trung": "Dành cho mọi thành viên mới bắt đầu hành trình học tập",
    "title_desc_Học Giả Bền Bỉ": "Đạt Level 5 - Chứng tỏ tinh thần học tập kiên trì",
    "title_desc_Chiến Binh Pomodoro": "Đạt Level 12 - Làm chủ kỹ năng quản lý thời gian",
    "title_desc_Bậc Thầy Tập Trung": "Đạt Level 25 - Khả năng siêu tập trung không xao nhãng",
    "title_desc_Đại Sứ Học Thuật": "Đạt Level 40 - Đỉnh cao tri thức và chuyên năng",
    "title_desc_Huyền Thoại XP": "Đạt Level 60 - Huyền thoại trong giới cày XP học tập",
    "title_desc_Thượng Cổ Thần Học": "Đạt Level 100 - Đỉnh phong chí tôn học giả",



    // payment & premium i18n vi
    premium_badge_vip: "Tài khoản VIP Premium",
    premium_modal_title: "Nâng cấp VIP Premium",
    premium_modal_subtitle: "Mở khóa trọn vẹn đặc quyền học tập đỉnh cao & thi đua cùng cộng đồng!",
    premium_select_package: "Chọn Gói Đăng Ký Thanh Toán:",
    premium_pkg_1m: "1 Tháng",
    premium_pkg_3m: "3 Tháng",
    premium_pkg_1y: "1 Năm",
    premium_tag_popular: "Phổ biến 🔥",
    premium_tag_save: "Tiết kiệm 25% ⚡",
    perk_scientific_timer: "Chế độ Đếm giờ Khoa học",
    perk_unlimited_lofi: "Nhạc Lofi Không Giới Hạn",
    perk_weekly_chart: "Biểu đồ Thống kê 7 Ngày",
    perk_xp_bonus: "Thưởng +15% XP & Huy hiệu VIP",
    btn_vnpay_pay: "Thanh toán VNPay / VNPAY-QR",
    btn_connecting_vnpay: "Đang kết nối VNPay...",
    btn_free_trial_3d: "Dùng thử nhanh 3 ngày (Test Miễn Phí)",
    btn_close: "Đóng",
    payment_success_title: "Thanh Toán Thành Công! 🎉",
    payment_success_desc: "Tài khoản của bạn đã được nâng cấp chính thức thành VIP Premium. Mọi đặc quyền cao cấp đã sẵn sàng!",
    payment_failed_title: "Thanh Toán Không Thành Công",
    payment_failed_desc: "Giao dịch thanh toán qua VNPay không thành công hoặc đã bị hủy. Vui lòng thử lại.",
    btn_back_to_home: "Trở về Trang chủ",
    payment_order_code: "Mã đơn hàng:",
    payment_history_title: "Lịch Sử Giao Dịch Thanh Toán VNPay",
    payment_history_no_orders: "Chưa có lịch sử giao dịch thanh toán nào.",
    payment_col_order_id: "Mã đơn hàng",
    payment_col_package: "Gói dịch vụ",
    payment_col_amount: "Số tiền",
    payment_col_status: "Trạng thái",
    payment_col_date: "Ngày tạo",
    payment_status_success: "Thành công",
    payment_status_pending: "Chờ xử lý",
    payment_status_expired: "Hết hạn",
    payment_status_failed: "Thất bại",
    profile_vip_active_badge: "Đặc Quyền VIP Đang Kích Hoạt",
    profile_btn_upgrade_vip: "Nâng cấp VIP Premium",
    profile_tab_premium: "VIP Premium",
    chart_vip_feature_tag: "Tính năng VIP",
    chart_lock_title: "Mở khóa Biểu đồ Thống kê 7 Ngày",
    chart_lock_desc: "Nâng cấp VIP Premium để xem phân tích số liệu học tập chuyên sâu 7 ngày qua!",
    chart_lock_upgrade_btn: "Nâng cấp Premium ngay",

    // Study Drive i18n
    drive_title: "Study Drive",
    drive_subtitle: "Lưu trữ tài liệu học tập đám mây",
    drive_back_dashboard: "Quay về Dashboard",
    drive_search_placeholder: "Tìm kiếm tài liệu học tập...",
    drive_create_folder: "Tạo Thư Mục",
    drive_upload_file: "Tải File Lên",
    upload_popup_title: "Tiến trình tải lên",
    upload_popup_warning: "Vui lòng không chuyển hoặc đóng màn hình trong thời gian tải file.",
    uploading_file: "Đang tải lên",
    upload_completed: "Tải lên thành công",
    upload_failed: "Tải lên thất bại",
    upload_file_count: "Tập tin {current}/{total}",
    toast_success_title: "Thành công",
    drive_upload_success_title: "Tải file thành công",
    drive_upload_success_desc: "Đã tải lên {count} tập tin thành công",
    error_file_size_exceeded: "Tập tin \"{name}\" vượt quá dung lượng tối đa 200 MB.",
    error_quota_exceeded: "Dung lượng bộ nhớ không đủ để lưu trữ file! (Còn trống: {available}, Tập tin: {required})",
    drive_tab_mydrive: "Drive Của Tôi",
    drive_tab_favorites: "Yêu Thích",
    drive_tab_trash: "Thùng Rác",
    drive_storage_header: "Bộ nhớ tài khoản",
    drive_used: "Đã dùng",
    drive_user_quota: "Hạn mức User: 1 GB",
    drive_max_file_size: "Max file size: 200 MB",
    drive_search_results_for: "Kết quả tìm kiếm cho:",
    drive_favorites_title: "Tài liệu Yêu Thích",
    drive_trash_title: "Thùng Rác",
    drive_grid_view: "Xem dạng Lưới",
    drive_list_view: "Xem dạng Danh sách",
    drive_empty_title: "Chưa có tài liệu nào ở đây",
    drive_empty_desc: "Kéo thả file vào đây hoặc nhấn nút 'Tải File Lên' để lưu trữ tài liệu học tập của bạn.",
    drive_empty_btn: "Tải File Đầu Tiên",
    drive_col_name: "Tên",
    drive_col_size: "Kích thước",
    drive_col_date: "Ngày tải lên",
    drive_col_actions: "Thao tác",
    drive_folder: "Thư mục",
    drive_restore: "Khôi phục",
    drive_perm_delete: "Xóa vĩnh viễn",
    drive_download: "Tải xuống",
    drive_rename: "Đổi tên",
    drive_delete: "Chuyển vào thùng rác",
    drive_modal_create_folder: "Tạo Thư Mục Mới",
    drive_modal_folder_placeholder: "Tên thư mục (ví dụ: Toán Cao Cấp)...",
    drive_btn_cancel: "Hủy",
    drive_btn_save: "Lưu",
    drive_modal_rename: "Đổi Tên",
    drive_preview_unsupported: "Định dạng file này không hỗ trợ xem trực tiếp",
    drive_preview_download_btn: "Tải về thiết bị để xem",
    nav_drive: "Tài liệu",
    nav_drive_title: "Drive tài liệu học tập",
  },
  en: {
    // auth / login / register
    login_title: "Study XP Tracker",
    login_subtitle: "Log in to continue grinding and leveling up!",
    email: "Email",
    password: "Password",
    login_btn: "Log In",
    logging_in: "Logging in...",
    no_account: "Don't have an account?",
    create_account: "Create new account",
    register_title: "Create Account",
    register_subtitle: "Start your journey to track study and level up!",
    display_name: "Display Name",
    confirm_password: "Confirm Password",
    register_btn: "Register",
    already_have_account: "Already have an account?",
    login_now: "Log In Now",
    passwords_dont_match: "Passwords do not match.",
    register_failed: "Registration failed. Please try again.",
    login_failed: "Login failed. Please check your credentials.",
    loading_account: "Loading account...",

    // friendly error messages (mapped from API error codes)
    error_invalid_credentials: "Incorrect email or password. Please try again.",
    error_account_not_found: "No account found with this email address.",
    error_email_already_exists: "This email is already in use. Please use a different email or log in.",
    error_invalid_input: "Invalid input. Please check your details and try again.",
    error_session_already_active: "You already have an active study session.",
    error_session_not_found: "Study session not found.",
    error_bad_request: "Invalid request. Please check your input.",
    error_unauthorized: "Your session has expired. Please log in again.",
    error_forbidden: "You do not have permission to perform this action.",
    error_not_found: "The requested resource was not found.",
    error_too_many_requests: "Too many attempts. Please wait a moment and try again.",
    error_server: "The server is experiencing issues. Please try again later.",
    error_unknown: "An unexpected error occurred. Please try again.",

    // dashboard layout & navbar
    logout: "Log Out",
    theme_light: "Light Mode",
    theme_dark: "Dark Mode",
    language: "Language",
    nav_messages: "Messages",
    nav_messages_title: "Messages Chat Window",
    nav_friends: "Friends",
    nav_friends_title: "Friends List",
    customize_dashboard: "Customize Layout",
    dashboard_customizer_title: "Dashboard Layout Settings",
    dashboard_customizer_desc: "Show or hide widgets to personalize your study space.",
    reset_default: "Show All Widgets",
    reset_order: "Reset Order",
    save_and_close: "Save & Close",
    drag_to_reorder: "Drag to reorder",
    widget_hidden_badge: "Hidden",
    widget_xpBar_name: "Level & XP Stats",
    widget_xpBar_desc: "Displays current level, accumulated XP, and level up progress",
    widget_studyTimer_name: "Study Timer",
    widget_studyTimer_desc: "Focus study timer with XP rewards",
    widget_manualSession_name: "Manual Study Log",
    widget_manualSession_desc: "Log offline study time or sessions when you forgot the timer",
    widget_onlineUsers_name: "Online Study Community",
    widget_onlineUsers_desc: "See fellow learners studying live with you",
    widget_countdown_name: "Exam Countdown",
    widget_countdown_desc: "Track remaining days for your upcoming major exams",
    widget_sessionHistory_name: "Study Journal",
    widget_sessionHistory_desc: "Review your recent completed study sessions",
    all_widgets_hidden: "All Widgets Hidden",
    all_widgets_hidden_desc: "Click the button below to open settings and choose widgets to display",

    // xp bar
    level: "Lvl",
    study_progress: "Study Progress",
    total_xp: "Total XP accumulated",
    xp_to_next: "needed to level up",
    session_active: "Estimated XP (Active Session)",
    session_saved: "Current XP",

    // study timer
    timer_title: "Study Timer",
    select_subject: "Select subject",
    timer_active_desc: "You are focusing on",
    timer_stopped_desc: "Timer is stopped",
    timer_placeholder: "Free / Other",
    btn_start: "Start Focus",
    btn_pause: "Pause",
    btn_resume: "Resume",
    btn_stop: "End & Claim XP",
    session_completed: "Session Completed",
    minutes: "mins",
    timer_start_error: "Could not start study session.",
    timer_stop_error: "Could not stop study session.",
    timer_counting: "Counting...",
    timer_ready: "Ready",
    timer_input_placeholder: "Subject / Topic (e.g. Math, Coding...)",
    timer_btn_start: "Start Focus",

    // study methods i18n
    select_method_title: "Study Method",
    method_free: "Free (Stopwatch)",
    method_pomodoro_25_5: "Pomodoro 25/5",
    method_pomodoro_50_10: "Pomodoro 50/10",
    method_rule_52_17: "52/17 Rule",
    method_deep_work_90_20: "Deep Work 90/20",
    method_active_recall_30_10: "Active Recall 30/10",
    method_free_desc: "Count up study time freely",
    method_pomodoro_25_5_desc: "25 min focus + 5 min break",
    method_pomodoro_50_10_desc: "50 min focus + 10 min break",
    method_rule_52_17_desc: "52 min focus + 17 min break",
    method_deep_work_90_20_desc: "90 min focus + 20 min break",
    method_active_recall_30_10_desc: "30 min active recall + 10 min review",
    break_time_title: "Relaxing Break Time ☕",
    break_time_desc: "Rest your eyes and relax before the next cycle!",
    bonus_xp_tag: "+15% Bonus XP",
    camera_presence_guard: "AI Presence Guard",
    camera_presence_guard_on: "AI Camera Guard: ON (+15% XP)",
    camera_presence_guard_off: "AI Camera Guard: OFF",
    status_present: "Present",
    status_absent: "Alert: Absent",
    camera_access_denied: "Camera access denied",
    camera_loading: "Initializing AI...",
    auto_pause_title: "Session Auto-Paused",
    auto_pause_desc: "Auto-paused because no user was detected in front of the camera for 5 minutes.",
    btn_resume_study: "I'm Back (Resume Study)",

    // manual session
    manual_title: "Manual Session Log",
    subject: "Subject",
    duration: "Duration (minutes)",
    btn_log: "Log Session",
    log_success: "Session logged successfully!",
    log_error: "Logging failed. Please try again.",
    hour: "hour",
    minute: "minute",
    second: "second",
    goal_log_error: "Could not automatically log study session",
    goal_duration_error: "Target duration must be greater than 0 seconds.",
    goal_countdown_title: "Set Countdown Goal",
    goal_subject_placeholder: "Math, Physics, Coding...",
    goal_duration_label: "Target Study Time",
    goal_btn_add: "Add New Goal",
    goal_list_title: "Set Goals",
    goal_no_goals: "No study goals set yet.",
    goal_status_completed: "Completed",
    goal_status_running: "Running",
    goal_status_paused: "Paused",
    goal_set_label: "Target:",
    goal_btn_start: "Start",
    goal_btn_delete: "Delete Goal",
    goal_completed_title: "Goal Completed! 🎉",
    goal_completed_desc: "Congratulations on completing your study goal for subject",
    goal_completed_in: "in",
    goal_btn_ok: "Awesome!",

    // countdown keys
    countdown_widget_title: "Target Day Countdown",
    countdown_subtitle: "Track upcoming exams and key milestones",
    countdown_select_preset: "Select preset exam / event",
    countdown_manage_btn: "Manage Countdowns",
    countdown_days: "days",
    countdown_hours: "hrs",
    countdown_minutes: "mins",
    countdown_seconds: "secs",
    countdown_official_badge: "Official Exam Schedule",
    countdown_estimated_badge: "Estimated (Auto-Sync)",
    countdown_add_new: "Create Custom Countdown",
    countdown_event_title: "Exam / Event Title",
    countdown_target_date: "Target Date & Time",
    countdown_note: "Target Notes",
    countdown_email_notify: "Send Email reminders when near milestone",
    countdown_pin: "Pin to Dashboard",
    countdown_unpin: "Unpin",
    countdown_delete: "Delete Countdown",
    countdown_save: "Save Changes",
    countdown_empty: "No countdown timers created yet.",
    countdown_tab_presets: "Community Events & Exams",
    countdown_tab_custom: "Your Countdowns",
    countdown_presets_desc: "Discover and track official exams & events created by fellow learners.",
    countdown_trackers_count: "trackers",
    countdown_trackers_count_suffix: "co-tracking this event",
    countdown_share_community: "🌐 Share with Community (Allow everyone to discover & track)",
    countdown_created_by: "Created by",
    countdown_community_badge: "Community",
    countdown_search_placeholder: "Search exams, events...",
    countdown_btn_track: "Track",

    countdown_btn_tracking: "Tracking",
    countdown_btn_untrack: "Untrack",
    countdown_pinned_badge: "Pinned",
    countdown_quote_normal: "Maintain consistent study habits every single day!",
    countdown_quote_warning: "⚡ Less than 30 days left! Speed up your practice exams!",
    countdown_quote_urgent: "🔥 Final countdown sprint! Stay strong and focused!",

    // preset exams i18n
    THPT_QG_2027_title: "National High School Graduation Exam 2027",
    THPT_QG_2027_desc: "Official annual national high school graduation exam",
    DGNL_HCMUT_2027_title: "HCMUT Competency Assessment Exam 2027",
    DGNL_HCMUT_2027_desc: "HCM University of Technology Competency Assessment Exam",
    DGNL_VNU_HCM_2027_title: "VNU-HCM Competency Assessment Exam (Round 1) 2027",
    DGNL_VNU_HCM_2027_desc: "Vietnam National University Ho Chi Minh City Competency Assessment",
    DGNL_HSA_VNU_HN_2027_title: "VNU-HN HSA Competency Assessment Exam 2027",
    DGNL_HSA_VNU_HN_2027_desc: "High School Student Competency Assessment by VNU Hanoi",
    TET_AM_2027_title: "Lunar New Year 2027 (Year of the Goat)",
    TET_AM_2027_desc: "Traditional Vietnamese Lunar New Year (Day 1)",


    // online users
    online_title: "Studying with You",
    online_users: "Online Users",
    no_online_users: "No one else is online studying right now.",
    level_short: "Lvl",
    total_xp_short: "Total XP",
    studying_subject: "Studying",
    status_active_idle: "Active (Idle)",
    no_online_short: "No one is online",

    // admin dashboard vi
    admin_dashboard: "Admin Dashboard",
    admin_subtitle: "Quản trị hệ thống, theo dõi online thời gian thực và thống kê học tập người dùng",
    admin_tab_online: "Đang Online (Realtime)",
    admin_tab_users_stats: "Thống Kê Task & Lịch Sử User",
    admin_stat_total_users: "Tổng Số Người Dùng",
    admin_stat_online_now: "Đang Online",
    admin_stat_studying_now: "Đang Học Tập",
    admin_stat_total_sessions: "Tổng Task/Session Hoàn Thành",
    admin_stat_total_hours: "Tổng Giờ Học Hệ Thống",
    admin_stat_total_xp: "Tổng XP Đã Phát",
    admin_search_placeholder: "Tìm kiếm theo tên hoặc email...",
    admin_status_filter_all: "Tất cả trạng thái",
    admin_status_filter_studying: "Đang học tập",
    admin_status_filter_idle: "Đang rảnh / Online",
    admin_period_all: "Tất cả thời gian",
    admin_period_today: "Hôm nay",
    admin_period_7d: "7 ngày qua",
    admin_period_30d: "30 ngày qua",
    admin_user_col_user: "Người dùng",
    admin_user_col_status: "Trạng thái",
    admin_user_col_level: "Level / XP",
    admin_user_col_sessions: "Số Sessions",
    admin_user_col_hours: "Tổng Giờ Học",
    admin_user_col_xp_period: "XP Tích Lũy",
    admin_user_col_last_active: "Hoạt Động Gần Nhất",
    admin_user_col_action: "Hành động",
    admin_view_history: "Xem Lịch Sử Task",
    admin_modal_history_title: "Chi Tiết Lịch Sử Task & Session Học Tập",
    admin_modal_no_sessions: "Người dùng này chưa có phiên học nào.",
    admin_session_col_subject: "Môn Học / Chủ Đề",
    admin_session_col_duration: "Thời Lượng",
    admin_session_col_xp: "XP Kiếm Được",
    admin_session_col_source: "Loại Session",
    admin_session_col_started: "Thời Gian Bắt Đầu",
    admin_session_source_timer: "Bấm giờ Timer",
    admin_session_source_manual: "Nhập thủ công",
    admin_role_admin: "Quản trị viên",
    admin_role_user: "Học viên",
    admin_btn_chat: "Tin Nhắn",
    admin_btn_search_user: "Tìm Người Dùng",
    admin_btn_send_msg: "Nhắn tin",
    admin_btn_reset_xp: "Reset 0 XP",
    admin_btn_ban: "Cấm",
    admin_btn_unban: "Mở khóa",
    admin_btn_history: "Lịch sử",
    admin_badge_banned: "⛔ Đã bị cấm",
    admin_badge_suspicious: "🚨 Bất thường",
    admin_account_menu_logout: "Đăng xuất",
    admin_account_menu_title: "Tài khoản Quản trị viên (Bấm để xem tùy chọn)",

    // Banned Notice Modal / Screen
    banned_notice_title: "Tài Khoản Đã Bị Khóa",
    banned_notice_subtitle: "Thông báo cấm tài khoản",
    banned_notice_reason_label: "Lý do bị cấm từ Ban Quản Trị:",
    banned_notice_default_reason: "Vi phạm quy chuẩn cộng đồng.",
    banned_notice_contact_support: "Tài khoản của bạn tạm thời không thể tham gia hệ thống. Nếu bạn tin rằng đây là sự nhầm lẫn, vui lòng gửi khiếu nại qua email hỗ trợ của Ban Quản Trị.",
    banned_notice_logout_btn: "Đăng Xuất Tài Khoản",

    // session history
    history_title: "Study History",
    no_sessions: "No sessions logged yet.",
    delete_confirm: "Are you sure you want to delete this session?",
    source_timer: "Timer",
    source_manual: "Manual",
    chart_minutes_label: "Minutes studied",
    chart_title: "Last 7 Days Statistics",
    no_sessions_subtitle: "Start the timer or add goals to begin grinding XP!",
    filter_all: "All",
    filter_today: "Today",
    filter_7d: "Last 7 days",
    filter_30d: "Last 30 days",
    filter_custom: "Pick a date",
    filter_title: "Filter by time:",
    no_filtered_sessions: "No sessions found for the selected time filter.",

    // study calendar
    calendar_title: "Study Calendar",
    one_year_past: "Past year",
    total_active_days: "Total study days",
    current_streak: "Current streak",
    longest_streak: "Longest streak",
    longest_streak_year: "Longest streak of year",
    total_duration: "Total duration",
    days: "days",
    hours: "hours",
    no_study_time: "No study time recorded",
    hover_tip: "Hover over cells to see session details",
    legend_less: "Less",
    legend_more: "More",
    weekdays: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],

    // landing page
    landing_slogan: "Free Gamified Study Tracker to Level Up Your Focus",
    landing_sub: "The best free online study tracker that converts every minute of learning into Experience Points (XP), features RPG level ups, Pomodoro timers, and real-time study rooms.",
    landing_cta_get_started: "Get Started",
    landing_cta_login: "Log In",
    landing_cta_features: "Explore Features",
    landing_mock_timer_title: "Test Drive the Timer & Claim XP",

    // member search & public profile
    search_members: "Search Members",
    search_members_placeholder: "Enter display name or email...",
    no_members_found: "No members found.",
    view_profile: "View Profile",
    public_profile_title: "Member Profile",
    member_level: "Level",
    member_streak: "Study Streak",
    member_total_time: "Total Study Time",
    member_total_sessions: "Completed Sessions",
    member_status_online: "Online",
    member_status_offline: "Offline",
    member_status_studying: "Currently Studying",
    member_bio_title: "Goal & Bio",
    member_no_bio: "This member has not set a bio yet.",
    close: "Close",
    landing_mock_timer_desc: "Click the button below to simulate a real study session.",
    landing_mock_btn_start: "Start Free Trial",
    landing_mock_btn_stop: "Stop & Claim XP!",
    landing_mock_level_up: "LEVEL UP! 🎉",
    landing_mock_xp_gained: "You gained",
    landing_mock_total_xp: "Mock Total XP",
    landing_feature_title: "Key Features",
    landing_feature_timer_title: "Anti-Cheat Pomodoro Timer",
    landing_feature_timer_desc: "Track study time down to the second. Built-in anti-cheat prevents time tampering via server-side verification.",
    landing_feature_rpg_title: "RPG Leveling Mechanics",
    landing_feature_rpg_desc: "Exciting level-up formula. Earn +10% bonus XP for high-focus sessions of 25 minutes or more.",
    landing_feature_coop_title: "Realtime Co-studying Room",
    landing_feature_coop_desc: "See other online users, their levels, and what they are studying in real-time to keep your fire burning.",
    landing_feature_heatmap_title: "Study Calendar & Streaks",
    landing_feature_heatmap_desc: "GitHub-style contribution heatmap and detailed charts to help you monitor your weekly progress.",
    landing_back_to_home: "Back to Home",
    landing_showcase_title: "Visually track your study progress",
    landing_showcase_desc: "The website provides a GitHub-style contribution calendar to automatically log your study streaks. It also integrates detailed 7-day charts using Recharts to help you easily evaluate your focus.",
    landing_showcase_item1: "Detailed daily stats of minutes studied",
    landing_showcase_item2: "Track current and longest streaks to keep your momentum going",
    landing_showcase_item3: "Easily log sessions manually if studying offline or forgot the timer",
    landing_showcase_btn: "Try It Now",
    landing_mock_streak: "Streaks",
    landing_mock_level: "Level",
    landing_mock_duration: "Hours Studied",
    landing_mock_heatmap_title: "Study Contribution Map (Heatmap)",
    landing_mock_coop_title: "Studying with You",
    landing_mock_user1_subject: "Studying Calculus",
    landing_mock_user2_subject: "Studying Java Programming",

    // rank i18n
    global_rank: "Rank",
    global_rank_unranked: "Unranked",
    global_rank_total_users: "users",

    // admin dashboard en
    admin_dashboard: "Admin Dashboard",
    admin_subtitle: "System management, realtime online tracking, and user study statistics",
    admin_tab_online: "Realtime Online",
    admin_tab_users_stats: "User Task & History Stats",
    admin_stat_total_users: "Total Registered Users",
    admin_stat_online_now: "Online Right Now",
    admin_stat_studying_now: "Currently Studying",
    admin_stat_total_sessions: "Total Completed Tasks/Sessions",
    admin_stat_total_hours: "Total System Study Hours",
    admin_stat_total_xp: "Total Distributed XP",
    admin_search_placeholder: "Search by name or email...",
    admin_status_filter_all: "All statuses",
    admin_status_filter_studying: "Studying",
    admin_status_filter_idle: "Active / Idle",
    admin_period_all: "All Time",
    admin_period_today: "Today",
    admin_period_7d: "Last 7 Days",
    admin_period_30d: "Last 30 Days",
    admin_user_col_user: "User",
    admin_user_col_status: "Status",
    admin_user_col_level: "Level / XP",
    admin_user_col_sessions: "Sessions",
    admin_user_col_hours: "Total Study Time",
    admin_user_col_xp_period: "Earned XP",
    admin_user_col_last_active: "Last Active",
    admin_user_col_action: "Action",
    admin_view_history: "View Task History",
    admin_modal_history_title: "Detailed Task & Session History",
    admin_modal_no_sessions: "This user has not logged any study sessions yet.",
    admin_session_col_subject: "Subject / Topic",
    admin_session_col_duration: "Duration",
    admin_session_col_xp: "Earned XP",
    admin_session_col_source: "Session Source",
    admin_session_col_started: "Started At",
    admin_session_source_timer: "Timer Mode",
    admin_session_source_manual: "Manual Mode",
    admin_role_admin: "Administrator",
    admin_role_user: "Learner",
    admin_btn_chat: "Messages",
    admin_btn_search_user: "Search Users",
    admin_btn_send_msg: "Send Message",
    admin_btn_reset_xp: "Reset 0 XP",
    admin_btn_ban: "Ban",
    admin_btn_unban: "Unban",
    admin_btn_history: "History",
    admin_badge_banned: "⛔ Banned",
    admin_badge_suspicious: "🚨 Suspicious",
    admin_account_menu_logout: "Log Out",
    admin_account_menu_title: "Administrator Account (Click for options)",

    // Banned Notice Modal / Screen
    banned_notice_title: "Account Suspended",
    banned_notice_subtitle: "Account Suspended Notice",
    banned_notice_reason_label: "Reason for ban from Admin:",
    banned_notice_default_reason: "Violation of community guidelines.",
    banned_notice_contact_support: "Your account is temporarily restricted from accessing the system. If you believe this is a mistake, please contact support via email.",
    banned_notice_logout_btn: "Log Out Account",

    // guest mode
    guest_login: "Guest Login",
    guest_login_btn: "Enter as Guest",
    guest_login_subtitle: "Enter a display name to try out the app instantly!",
    guest_name_label: "Your Display Name",
    guest_name_placeholder: "e.g., Diligent Guest...",
    guest_badge: "Guest Account",
    guest_overlay_title: "Create an account to save study history",
    guest_overlay_desc: "You are currently in Guest mode. Register now to unlock 7-Day Stats, Heatmap, and save all your study progress!",
    guest_register_cta: "Register & Save Progress",

    // footer author info
    footer_author_title: "Author Information",
    footer_author_name: "Author",
    footer_contact_email: "Contact Email",
    footer_address: "Address",
    footer_copyright: "Gamified learning application to track study hours, level up XP, and build long-term study habits.",

    // user profile & settings
    profile_seo_title: "Profile & Settings - Study XP Tracker",
    profile_seo_desc: "Manage account settings, avatar, titles, and customize your study experience.",
    back_to_dashboard: "Back to Dashboard",
    profile_user_default: "User",
    profile_total_xp: "Total XP:",
    profile_daily_goal: "Daily Goal:",
    profile_tab_info: "Personal Profile",
    profile_tab_security: "Security & Password",
    profile_tab_titles: "RPG Titles",
    profile_tab_preferences: "Preferences",
    profile_edit_info: "Edit Profile Information",
    profile_display_name_label: "Display Name:",
    profile_display_name_placeholder: "e.g. John Doe",
    profile_daily_goal_label: "Daily Study Goal (Minutes):",
    profile_goal_30: "30 mins / day (Basic)",
    profile_goal_60: "60 mins / day (Standard)",
    profile_goal_90: "90 mins / day (Accelerated)",
    profile_goal_120: "120 mins / day (Hardworking)",
    profile_goal_180: "180 mins / day (Master)",
    profile_favorite_subjects_label: "Favorite Subjects / Topics:",
    profile_favorite_subjects_placeholder: "e.g. Java, English, Mathematics...",
    profile_bio_label: "Bio / Personal Motto:",
    profile_bio_placeholder: "Share your study goals or motto...",
    profile_char_limit: "chars",
    profile_btn_save: "Save Changes",
    profile_saving: "Saving...",
    profile_security_title: "Security & Password Management",
    profile_google_title: "Google Signed-In Account",
    profile_google_desc: "This account is linked via Google OAuth2. Your password is securely managed by Google.",
    profile_current_password: "Current Password:",
    profile_new_password: "New Password (Min 6 chars):",
    profile_confirm_password: "Confirm New Password:",
    profile_btn_change_password: "Change Password",
    profile_processing: "Processing...",
    profile_titles_title: "RPG Study Titles",
    profile_titles_desc: "Increase your study level to unlock exclusive titles and equip them publicly!",
    profile_title_unlocked: "Unlocked",
    profile_title_req_lvl: "Req. Lvl",
    profile_title_equipped: "Equipped",
    profile_title_equip_btn: "Equip Title",
    profile_preferences_title: "Preferences & Appearance",
    profile_theme_accent_label: "Theme Accent Color:",
    profile_accent_indigo: "Indigo (Default)",
    profile_accent_emerald: "Emerald Green",
    profile_accent_rose: "Rose Red",
    profile_accent_amber: "Amber Gold",
    profile_accent_purple: "Royal Purple",
    profile_system_language_label: "System Language:",
    profile_sound_fx_title: "Sound Effects (Sound FX)",
    profile_sound_fx_desc: "Play celebration sounds when completing Pomodoro or Leveling Up.",
    profile_privacy_status_title: "Activity Status Privacy",
    profile_privacy_status_desc: "Choose who can see your Online & Active Study status.",
    profile_privacy_everyone_title: "Public (Everyone)",
    profile_privacy_everyone_desc: "All members can see when you are online or studying.",
    profile_privacy_friends_title: "Friends Only",
    profile_privacy_friends_desc: "Only accepted friends can see your online/study status.",
    profile_privacy_nobody_title: "Private (Nobody)",
    profile_privacy_nobody_desc: "No one can see your online or active study session status.",
    profile_message_permission_title: "Direct Message Privacy",
    profile_message_permission_desc: "Choose who can send you direct messages in Study XP Tracker.",
    profile_msg_everyone_title: "Everyone",
    profile_msg_everyone_desc: "Any member can send you direct messages.",
    profile_msg_friends_title: "Friends Only",
    profile_msg_friends_desc: "Only accepted friends can send you direct messages.",
    profile_msg_nobody_title: "Nobody",
    profile_msg_nobody_desc: "Block all incoming direct messages from everyone.",
    profile_theme_mode_title: "Theme Appearance",
    profile_theme_mode_desc: "Switch between Light and Dark mode appearance for the system.",
    profile_theme_light_label: "Light Mode",
    profile_theme_dark_label: "Dark Mode",
    profile_logout_desc: "Log out of your current active session on this device.",
    profile_btn_save_settings: "Save Settings",
    profile_toast_info_success: "Personal information updated successfully.",
    profile_toast_avatar_success: "New profile avatar updated successfully.",
    profile_toast_preset_avatar_success: "Avatar changed successfully.",
    profile_toast_password_success: "Password changed successfully. Please remember your new password.",
    profile_toast_title_success: "Equipped title",

    // avatar uploader en
    avatar_title: "Profile Avatar",
    avatar_desc: "Upload an image from your device or pick an RPG avatar preset.",
    avatar_tab_upload: "Upload Image",
    avatar_tab_preset: "RPG Avatar Library",
    avatar_tab_generator: "Random Generator",
    avatar_drag_drop: "Drag & drop your file here or click to upload",
    avatar_support_formats: "Supports PNG, JPG, WEBP (auto-compressed under 5MB)",
    avatar_btn_cancel: "Cancel Selection",
    avatar_btn_save: "Save Profile Picture",
    avatar_preset_subtitle: "Choose an RPG cartoon avatar from below:",
    avatar_gen_style: "Style:",
    avatar_gen_seed: "Keyword (Seed / Name):",
    avatar_gen_btn: "Generate New",
    avatar_gen_preview: "Preview generated avatar",
    avatar_gen_use: "Use This Avatar",
    avatar_cancel_tooltip: "Cancel file selection",

    // rpg titles i18n
    "title_Tân Binh Tập Trung": "Focus Novice",
    "title_Học Giả Bền Bỉ": "Persistent Scholar",
    "title_Chiến Binh Pomodoro": "Pomodoro Warrior",
    "title_Bậc Thầy Tập Trung": "Focus Master",
    "title_Đại Sứ Học Thuật": "Academic Ambassador",
    "title_Huyền Thoại XP": "XP Legend",
    "title_Thượng Cổ Thần Học": "Ancient Overlord",

    "title_desc_Tân Binh Tập Trung": "For all new members starting their study journey",
    "title_desc_Học Giả Bền Bỉ": "Reach Level 5 - Demonstrate persistent study spirit",
    "title_desc_Chiến Binh Pomodoro": "Reach Level 12 - Master time management skills",
    "title_desc_Bậc Thầy Tập Trung": "Reach Level 25 - Super focus capability without distraction",
    "title_desc_Đại Sứ Học Thuật": "Reach Level 40 - Pinnacle of knowledge and dedication",
    "title_desc_Huyền Thoại XP": "Reach Level 60 - A true legend in XP study grinding",
    "title_desc_Thượng Cổ Thần Học": "Reach Level 100 - Ultimate supreme scholar milestone",



    // payment & premium i18n en
    premium_badge_vip: "VIP Premium Account",
    premium_modal_title: "Upgrade to VIP Premium",
    premium_modal_subtitle: "Unlock full premium study perks & compete with the community!",
    premium_select_package: "Select Subscription Package:",
    premium_pkg_1m: "1 Month",
    premium_pkg_3m: "3 Months",
    premium_pkg_1y: "1 Year",
    premium_tag_popular: "Popular 🔥",
    premium_tag_save: "Save 25% ⚡",
    perk_scientific_timer: "Scientific Focus Timer",
    perk_unlimited_lofi: "Unlimited Lofi Music",
    perk_weekly_chart: "7-Day Analytical Chart",
    perk_xp_bonus: "+15% XP Bonus & VIP Badge",
    btn_vnpay_pay: "Pay via VNPay / VNPAY-QR",
    btn_connecting_vnpay: "Connecting to VNPay...",
    btn_free_trial_3d: "Quick 3-Day Free Trial",
    btn_close: "Close",
    payment_success_title: "Payment Successful! 🎉",
    payment_success_desc: "Your account has been officially upgraded to VIP Premium. All exclusive perks are now active!",
    payment_failed_title: "Payment Failed",
    payment_failed_desc: "The VNPay payment transaction failed or was cancelled. Please try again.",
    btn_back_to_home: "Return to Home",
    payment_order_code: "Order ID:",
    payment_history_title: "VNPay Payment Transaction History",
    payment_history_no_orders: "No payment transaction history yet.",
    payment_col_order_id: "Order ID",
    payment_col_package: "Package",
    payment_col_amount: "Amount",
    payment_col_status: "Status",
    payment_col_date: "Date Created",
    payment_status_success: "Successful",
    payment_status_pending: "Pending",
    payment_status_expired: "Expired",
    payment_status_failed: "Failed",
    profile_vip_active_badge: "VIP Perks Active",
    profile_btn_upgrade_vip: "Upgrade to VIP Premium",
    profile_tab_premium: "VIP Premium",
    chart_vip_feature_tag: "VIP Feature",
    chart_lock_title: "Unlock 7-Day Analytical Chart",
    chart_lock_desc: "Upgrade to VIP Premium to view weekly in-depth study analytics!",
    chart_lock_upgrade_btn: "Upgrade to Premium Now",

    // Study Drive i18n
    drive_title: "Study Drive",
    drive_subtitle: "Cloud Study Documents Storage",
    drive_back_dashboard: "Back to Dashboard",
    drive_search_placeholder: "Search study documents...",
    drive_create_folder: "Create Folder",
    drive_upload_file: "Upload File",
    upload_popup_title: "Upload Progress",
    upload_popup_warning: "Please do not close or switch screen during file upload.",
    uploading_file: "Uploading",
    upload_completed: "Upload completed",
    upload_failed: "Upload failed",
    upload_file_count: "File {current}/{total}",
    toast_success_title: "Success",
    drive_upload_success_title: "Upload Successful",
    drive_upload_success_desc: "Successfully uploaded {count} file(s)",
    error_file_size_exceeded: "File \"{name}\" exceeds maximum size limit of 200 MB.",
    error_quota_exceeded: "Insufficient storage quota! (Available: {available}, Required: {required})",
    drive_tab_mydrive: "My Drive",
    drive_tab_favorites: "Favorites",
    drive_tab_trash: "Trash",
    drive_storage_header: "Account Storage",
    drive_used: "Used",
    drive_user_quota: "User Quota: 1 GB",
    drive_max_file_size: "Max file size: 200 MB",
    drive_search_results_for: "Search results for:",
    drive_favorites_title: "Favorite Documents",
    drive_trash_title: "Trash",
    drive_grid_view: "Grid View",
    drive_list_view: "List View",
    drive_empty_title: "No documents here yet",
    drive_empty_desc: "Drag & drop files here or click 'Upload File' to store your learning documents.",
    drive_empty_btn: "Upload First File",
    drive_col_name: "Name",
    drive_col_size: "Size",
    drive_col_date: "Date Uploaded",
    drive_col_actions: "Actions",
    drive_folder: "Folder",
    drive_restore: "Restore",
    drive_perm_delete: "Permanent Delete",
    drive_download: "Download",
    drive_rename: "Rename",
    drive_delete: "Move to Trash",
    drive_modal_create_folder: "Create New Folder",
    drive_modal_folder_placeholder: "Folder name (e.g. Advanced Calculus)...",
    drive_btn_cancel: "Cancel",
    drive_btn_save: "Save",
    drive_modal_rename: "Rename",
    drive_preview_unsupported: "Direct preview is not supported for this file format",
    drive_preview_download_btn: "Download to device to view",
    nav_drive: "Documents",
    nav_drive_title: "Study Documents Drive",
  },
  zh: {
    // auth / login / register
    login_title: "学习经验值追踪器",
    login_subtitle: "登录以继续努力学习并升级！",
    email: "电子邮件",
    password: "密码",
    login_btn: "登录",
    logging_in: "正在登录...",
    no_account: "还没有账户？",
    create_account: "创建新账户",
    register_title: "创建账户",
    register_subtitle: "开始您的学习追踪和升级之旅！",
    display_name: "显示名称",
    confirm_password: "确认密码",
    register_btn: "注册",
    already_have_account: "已有账户？",
    login_now: "立即登录",
    passwords_dont_match: "密码不匹配。",
    register_failed: "注册失败。请重试。",
    login_failed: "登录失败。请检查您的凭据。",
    loading_account: "正在加载账户...",

    // friendly error messages (mapped from API error codes)
    error_invalid_credentials: "电子邮件或密码不正确，请重试。",
    error_account_not_found: "未找到使用此电子邮件的账户。",
    error_email_already_exists: "此电子邮件已被使用。请使用其他邮件或直接登录。",
    error_invalid_input: "输入无效，请检查您的信息后重试。",
    error_session_already_active: "您已有一个正在进行的学习会话。",
    error_session_not_found: "未找到该学习会话。",
    error_bad_request: "请求无效，请检查您的输入。",
    error_unauthorized: "您的登录会话已过期，请重新登录。",
    error_forbidden: "您没有权限执行此操作。",
    error_not_found: "未找到所请求的资源。",
    error_too_many_requests: "尝试次数过多，请稍等片刻后再试。",
    error_server: "服务器遇到问题，请稍后重试。",
    error_unknown: "发生了未知错误，请重试。",

    // dashboard layout & navbar
    logout: "退出登录",
    theme_light: "浅色模式",
    theme_dark: "深色模式",
    language: "语言",
    nav_messages: "消息",
    nav_messages_title: "消息聊天窗口",
    nav_friends: "好友",
    nav_friends_title: "好友列表",
    customize_dashboard: "自定义界面",
    dashboard_customizer_title: "仪表盘界面设置",
    dashboard_customizer_desc: "开启/关闭您希望在学习屏幕上显示的组件。",
    reset_default: "显示全部组件",
    reset_order: "重置顺序",
    save_and_close: "保存并关闭",
    drag_to_reorder: "拖动调整顺序",
    widget_hidden_badge: "已隐藏",
    widget_xpBar_name: "等级与经验值",
    widget_xpBar_desc: "显示当前等级、累计经验值及升级进度",
    widget_studyTimer_name: "学习计时器",
    widget_studyTimer_desc: "专注学习计时并获得经验值奖励",
    widget_manualSession_name: "补录学习记录",
    widget_manualSession_desc: "离线学习或忘记计时时手动补录学习时长",
    widget_onlineUsers_name: "在线自习战友",
    widget_onlineUsers_desc: "查看与您一同在线专注学习的同学与好友",
    widget_countdown_name: "考试倒计时",
    widget_countdown_desc: "追踪重要考试的剩余倒计时天数",
    widget_sessionHistory_name: "学习日志",
    widget_sessionHistory_desc: "回顾您近期完成的学习记录列表",
    all_widgets_hidden: "您已隐藏所有组件",
    all_widgets_hidden_desc: "点击下方按钮重新打开设置并选择要显示的组件",

    // xp bar
    level: "等级",
    study_progress: "学习进度",
    total_xp: "累计总经验值",
    xp_to_next: "升级所需",
    session_active: "预估经验值 (正在学习)",
    session_saved: "当前经验值",

    // study timer
    timer_title: "学习计时器",
    select_subject: "选择科目",
    timer_active_desc: "您正在专注于",
    timer_stopped_desc: "计时器已停止",
    timer_placeholder: "自由 / 其他",
    btn_start: "开始专注",
    btn_pause: "暂停",
    btn_resume: "继续",
    btn_stop: "结束并领取经验值",
    session_completed: "学习已完成",
    minutes: "分钟",
    timer_start_error: "无法开始学习。",
    timer_stop_error: "无法停止学习。",
    timer_counting: "正在计时...",
    timer_ready: "准备就绪",
    timer_input_placeholder: "科目 / 主题 (例如: 数学, 编程...)",
    timer_btn_start: "开始学习",
    camera_presence_guard: "AI出席确认",
    camera_presence_guard_on: "AI摄像头守卫：已开启 (+15% XP)",
    camera_presence_guard_off: "AI摄像头守卫：已关闭",
    status_present: "在位",
    status_absent: "警告：缺席",
    camera_access_denied: "无法访问摄像头",
    camera_loading: "正在初始化AI...",
    auto_pause_title: "学习已自动暂停",
    auto_pause_desc: "由于5分钟内未在摄像头前检测到您，已自动暂停。",
    btn_resume_study: "我回来了 (继续学习)",

    // manual session
    manual_title: "手动记录学习",
    subject: "科目",
    duration: "学习时长 (分钟)",
    btn_log: "记录学习",
    log_success: "学习记录成功！",
    log_error: "记录失败。请重试。",
    hour: "小时",
    minute: "分钟",
    second: "秒",
    goal_log_error: "无法自动记录学习",
    goal_duration_error: "目标时长必须大于0秒。",
    goal_countdown_title: "设置倒计时目标",
    goal_subject_placeholder: "数学, 物理, 编程...",
    goal_duration_label: "目标学习时间",
    goal_btn_add: "添加新目标",
    goal_list_title: "已设定的目标",
    goal_no_goals: "尚未设定学习目标。",
    goal_status_completed: "已完成",
    goal_status_running: "正在进行",
    goal_status_paused: "已暂停",
    goal_set_label: "设定目标:",
    goal_btn_start: "开始",
    goal_btn_delete: "删除目标",
    goal_completed_title: "目标已完成！🎉",
    goal_completed_desc: "恭喜您成功完成了学习目标：",
    goal_completed_in: "用时",
    goal_btn_ok: "太棒了！",

    // countdown keys
    countdown_widget_title: "目标倒计时",
    countdown_subtitle: "追踪即将到来的考试和关键里程碑",
    countdown_select_preset: "选择预设考试 / 活动",
    countdown_manage_btn: "管理倒计时",
    countdown_days: "天",
    countdown_hours: "小时",
    countdown_minutes: "分钟",
    countdown_seconds: "秒",
    countdown_official_badge: "官方正式考试日程",
    countdown_estimated_badge: "预估日程 (Auto-Sync)",
    countdown_add_new: "创建自定义倒计时",
    countdown_event_title: "考试 / 活动名称",
    countdown_target_date: "目标日期与时间",
    countdown_note: "目标备注",
    countdown_email_notify: "临近里程碑时发送邮件提醒",
    countdown_pin: "固定到仪表板",
    countdown_unpin: "取消固定",
    countdown_delete: "删除倒计时",
    countdown_save: "保存更改",
    countdown_empty: "尚未创建倒计时定时器。",
    countdown_tab_presets: "社区活动与考试",
    countdown_tab_custom: "您的倒计时",
    countdown_presets_desc: "探索并追踪官方考试以及其他同伴发布的社区活动。",
    countdown_trackers_count: "人正在关注",
    countdown_trackers_count_suffix: "人共同关注",
    countdown_share_community: "🌐 分享至社区 (允许大家公开查看并共同关注)",
    countdown_created_by: "创建者",
    countdown_community_badge: "社区",
    countdown_search_placeholder: "搜索考试、活动...",
    countdown_btn_track: "追踪",

    countdown_btn_tracking: "正在追踪",
    countdown_btn_untrack: "取消追踪",
    countdown_pinned_badge: "已固定",
    countdown_quote_normal: "坚持每天良好的学习习惯！",
    countdown_quote_warning: "⚡ 距离考试不足30天！加速做题冲刺！",
    countdown_quote_urgent: "🔥 最后的冲刺倒计时！保持状态！",

    // preset exams i18n
    THPT_QG_2027_title: "2027年越南全国高中毕业考试",
    THPT_QG_2027_desc: "每年官方全国高中毕业考试",
    DGNL_HCMUT_2027_title: "2027年胡志明市理工大学能力评估考试",
    DGNL_HCMUT_2027_desc: "胡志明市理工大学能力评估考试",
    DGNL_VNU_HCM_2027_title: "2027年胡志明市国家大学能力评估考试 (第一批)",
    DGNL_VNU_HCM_2027_desc: "胡志明市国家大学能力评估考试",
    DGNL_HSA_VNU_HN_2027_title: "2027年河内国家大学HSA能力评估考试",
    DGNL_HSA_VNU_HN_2027_desc: "河内国家大学高中生能力评估考试",
    TET_AM_2027_title: "2027年丁未年农历春节",
    TET_AM_2027_desc: "越南传统农历新年 (大年初一)",



    // online users
    online_title: "正在和你一起学习",
    online_users: "在线用户",
    no_online_users: "目前没有其他人在在线学习。",
    level_short: "等级",
    total_xp_short: "总经验",
    studying_subject: "正在学习",
    status_active_idle: "活跃 (空闲)",
    no_online_short: "没有在线用户",

    // session history
    history_title: "学习历史",
    no_sessions: "尚无学习记录。",
    delete_confirm: "您确定要删除此学习记录吗？",
    source_timer: "计时器",
    source_manual: "手动",
    chart_minutes_label: "学习分钟数",
    chart_title: "最近7天统计",
    no_sessions_subtitle: "启动计时器或添加目标以开始积累经验值！",

    // study calendar
    calendar_title: "学习日历",
    one_year_past: "过去一年",
    total_active_days: "总学习天数",
    current_streak: "当前连续天数",
    longest_streak: "最长连续天数",
    longest_streak_year: "年度最长连续天数",
    total_duration: "总时长",
    days: "天",
    hours: "小时",
    no_study_time: "未记录学习时间",
    hover_tip: "将鼠标悬停在单元格上以查看学习详情",
    legend_less: "少",
    legend_more: "多",
    weekdays: ["日", "一", "二", "三", "四", "五", "六"],

    // landing page
    landing_slogan: "提升您的学习之旅",
    landing_sub: "将您学习的每一分钟转化为经验值（XP），像RPG角色一样升级，并与在线学习伙伴一起奋斗。",
    landing_cta_get_started: "开始挑战",
    landing_cta_login: "登录",
    landing_cta_features: "探索功能",
    landing_mock_timer_title: "试用计时器并领取经验值",
    landing_mock_timer_desc: "点击下方按钮模拟真实的学习过程。",
    landing_mock_btn_start: "开始试用",
    landing_mock_btn_stop: "停止并领取经验值！",
    landing_mock_level_up: "恭喜升级！🎉",
    landing_mock_xp_gained: "您获得了",
    landing_mock_total_xp: "模拟总经验",
    landing_feature_title: "主要功能",
    landing_feature_timer_title: "防作弊番茄计时器",
    landing_feature_timer_desc: "精确记录每一秒的学习时间。通过服务器端验证防止篡改时间，内置防作弊机制。",
    landing_feature_rpg_title: "RPG 游戏升级机制",
    landing_feature_rpg_desc: "有趣的升级公式。专注学习25分钟或以上，可额外获得10%的经验值奖励。",
    landing_feature_coop_title: "实时协同学习",
    landing_feature_coop_desc: "实时查看其他在线用户、他们的等级以及他们正在学习的内容，保持学习热情。",
    landing_feature_heatmap_title: "学习日历与连续天数",
    landing_feature_heatmap_desc: "类 GitHub 贡献热力图和详细的统计图表，帮助您监控每周的学习进度。",
    landing_back_to_home: "返回主页",
    landing_showcase_title: "直观地追踪您的学习进度",
    landing_showcase_desc: "网站提供类似 GitHub 的学习日历，自动记录您的连续学习天数。它还集成基于 Recharts 的 7 天统计图表，帮助您轻松评估专注度。",
    landing_showcase_item1: "每日学习分钟数的详细统计",
    landing_showcase_item2: "追踪当前和最长连续学习天数，保持奋斗动力",
    landing_showcase_item3: "离线学习或忘记启动计时器时，轻松手动记录",
    landing_showcase_btn: "立即体验",
    landing_mock_streak: "连续天数",
    landing_mock_level: "等级",
    landing_mock_duration: "学习时长",
    landing_mock_heatmap_title: "学习贡献图 (热力图)",
    landing_mock_coop_title: "正在和你一同学习",
    landing_mock_user1_subject: "正在学习微积分",
    landing_mock_user2_subject: "正在学习 Java 编程",

    // guest mode
    guest_login: "游客登录",
    guest_login_btn: "以游客身份进入",
    guest_login_subtitle: "只需输入显示名称即可立即体验！",
    guest_name_label: "您的显示名称",
    guest_name_placeholder: "例如: 勤奋的游客...",
    guest_badge: "游客账户",
    guest_overlay_title: "创建账户以保存学习记录",
    guest_overlay_desc: "您目前正在使用游客账户。立即注册账户以解锁7天统计、热力图并保存全部学习进度！",
    guest_register_cta: "注册并保存进度",

    // footer author info
    footer_author_title: "作者信息",
    footer_author_name: "作者",
    footer_contact_email: "联系邮箱",
    footer_address: "地址",
    footer_copyright: "游戏化学习应用，用于跟踪学习时间、提升 XP 等级并建立长期学习习惯。",

    // user profile & settings
    profile_seo_title: "个人资料与设置 - Study XP Tracker",
    profile_seo_desc: "管理账户设置、头像、称号并自定义您的学习体验。",
    back_to_dashboard: "返回控制台",
    profile_user_default: "用户",
    profile_total_xp: "累计经验:",
    profile_daily_goal: "每日目标:",
    profile_tab_info: "个人资料",
    profile_tab_security: "安全与密码",
    profile_tab_titles: "RPG 称号",
    profile_tab_preferences: "偏好设置",
    profile_edit_info: "编辑个人信息",
    profile_display_name_label: "显示名称：",
    profile_display_name_placeholder: "例如：张三",
    profile_daily_goal_label: "每日学习目标（分钟）：",
    profile_goal_30: "30 分钟 / 天（基础）",
    profile_goal_60: "60 分钟 / 天（标准）",
    profile_goal_90: "90 分钟 / 天（加速）",
    profile_goal_120: "120 分钟 / 天（勤奋）",
    profile_goal_180: "180 分钟 / 天（大师）",
    profile_favorite_subjects_label: "最喜欢的科目/主题：",
    profile_favorite_subjects_placeholder: "例如：Java编程，英语，高等数学...",
    profile_bio_label: "个人简介 / 座右铭：",
    profile_bio_placeholder: "分享您的学习目标或个人座右铭...",
    profile_char_limit: "字符",
    profile_btn_save: "保存更改",
    profile_saving: "保存中...",
    profile_security_title: "安全与密码管理",
    profile_google_title: "Google 登录账号",
    profile_google_desc: "此账号已关联 Google OAuth2 登录。您的密码由 Google 安全管理。",
    profile_current_password: "当前密码：",
    profile_new_password: "新密码（至少 6 个字符）：",
    profile_confirm_password: "确认新密码：",
    profile_btn_change_password: "修改密码",
    profile_processing: "处理中...",
    profile_titles_title: "RPG 学习称号",
    profile_titles_desc: "提升您的学习等级以解锁独家称号并公开佩戴！",
    profile_title_unlocked: "已解锁",
    profile_title_req_lvl: "需要等级",
    profile_title_equipped: "佩戴中",
    profile_title_equip_btn: "佩戴称号",
    profile_preferences_title: "偏好与外观设置",
    profile_theme_accent_label: "主题强调色：",
    profile_accent_indigo: "靛蓝（默认）",
    profile_accent_emerald: "翡翠绿",
    profile_accent_rose: "玫瑰红",
    profile_accent_amber: "琥珀金",
    profile_accent_purple: "皇家紫",
    profile_system_language_label: "系统语言：",
    profile_sound_fx_title: "音效（Sound FX）",
    profile_sound_fx_desc: "完成番茄钟或升级时播放庆祝音效。",
    profile_privacy_status_title: "活动状态隐私设置",
    profile_privacy_status_desc: "设置其他用户是否可以看到您的在线与学习状态。",
    profile_privacy_everyone_title: "公开（所有人）",
    profile_privacy_everyone_desc: "所有成员都可以看到您的在线或学习状态。",
    profile_privacy_friends_title: "仅限好友",
    profile_privacy_friends_desc: "只有互加好友的用户才能看到您的在线/学习状态。",
    profile_privacy_nobody_title: "隐身（所有人不可见）",
    profile_privacy_nobody_desc: "任何人都无法看到您的在线或学习状态。",
    profile_message_permission_title: "私信接收权限",
    profile_message_permission_desc: "设置在 Study XP Tracker 中谁可以向您发送私信。",
    profile_msg_everyone_title: "所有人",
    profile_msg_everyone_desc: "任何用户都可以向您发送私信。",
    profile_msg_friends_title: "仅限好友",
    profile_msg_friends_desc: "仅已互加好友的用户可以向您发送私信。",
    profile_msg_nobody_title: "关闭私信",
    profile_msg_nobody_desc: "拒绝接收任何人的私信。",
    profile_theme_mode_title: "界面主题模式",
    profile_theme_mode_desc: "在系统浅色与深色外观之间进行切换。",
    profile_theme_light_label: "浅色模式 (Light Mode)",
    profile_theme_dark_label: "深色模式 (Dark Mode)",
    profile_logout_desc: "从此设备上的当前会话中退出登录。",
    profile_btn_save_settings: "保存设置",
    profile_toast_info_success: "个人信息更新成功。",
    profile_toast_avatar_success: "头像更新成功。",
    profile_toast_preset_avatar_success: "头像更改成功。",
    profile_toast_password_success: "密码修改成功，请牢记新密码。",
    profile_toast_title_success: "已佩戴称号",

    // avatar uploader zh
    avatar_title: "个人头像",
    avatar_desc: "从您的设备上传图片或选择 RPG 卡通头像。",
    avatar_tab_upload: "上传图片",
    avatar_tab_preset: "RPG 头像库",
    avatar_tab_generator: "随机生成",
    avatar_drag_drop: "拖放文件到此处或点击上传",
    avatar_support_formats: "支持 PNG, JPG, WEBP（自动压缩至 5MB 以下）",
    avatar_btn_cancel: "取消选择",
    avatar_btn_save: "保存头像",
    avatar_preset_subtitle: "在下方选择一个 RPG 风格卡通头像：",
    avatar_gen_style: "风格：",
    avatar_gen_seed: "关键字 (Seed)：",
    avatar_gen_btn: "生成新头像",
    avatar_gen_preview: "预览生成的头像",
    avatar_gen_use: "使用此头像",
    avatar_cancel_tooltip: "取消选择",

    // rpg titles i18n
    "title_Tân Binh Tập Trung": "专注新手",
    "title_Học Giả Bền Bỉ": "坚持学者",
    "title_Chiến Binh Pomodoro": "番茄战士",
    "title_Bậc Thầy Tập Trung": "专注大师",
    "title_Đại Sứ Học Thuật": "学术大使",
    "title_Huyền Thoại XP": "XP 传奇",
    "title_Thượng Cổ Thần Học": "远古学神",

    "title_desc_Tân Binh Tập Trung": "适合所有刚开始学习之旅的新成员",
    "title_desc_Học Giả Bền Bỉ": "达到 5 级 - 展示坚持不懈的学习精神",
    "title_desc_Chiến Binh Pomodoro": "达到 12 级 - 掌握时间管理技能",
    "title_desc_Bậc Thầy Tập Trung": "达到 25 级 - 具备无干扰的高度专注能力",
    "title_desc_Đại Sứ Học Thuật": "达到 40 级 - 知识与专注力的巅峰",
    "title_desc_Huyền Thoại XP": "达到 60 级 - 学习经验值刷级界的传奇",
    "title_desc_Thượng Cổ Thần Học": "达到 100 级 - 终极至尊学者里程碑",



    // Banned Notice Modal / Screen
    banned_notice_title: "账号已被封禁",
    banned_notice_subtitle: "账号封禁通知",
    banned_notice_reason_label: "管理员封禁原因：",
    banned_notice_default_reason: "违反社区准则。",
    banned_notice_contact_support: "您的账号暂时无法访问系统。如果您认为这是一个误会，请发送电子邮件至支持团队进行申诉。",
    banned_notice_logout_btn: "退出账号",

    // payment & premium i18n zh
    premium_badge_vip: "VIP Premium 账户",
    premium_modal_title: "升级 VIP Premium",
    premium_modal_subtitle: "解锁全套高级学习特权，与社区共同竞争！",
    premium_select_package: "选择订阅套餐：",
    premium_pkg_1m: "1 个月",
    premium_pkg_3m: "3 个月",
    premium_pkg_1y: "1 年",
    premium_tag_popular: "热门 🔥",
    premium_tag_save: "省 25% ⚡",
    perk_scientific_timer: "科学专注计时",
    perk_unlimited_lofi: "无限 Lofi 音乐",
    perk_weekly_chart: "7 天分析图表",
    perk_xp_bonus: "+15% XP 奖励与 VIP 徽章",
    btn_vnpay_pay: "通过 VNPay / VNPAY-QR 支付",
    btn_connecting_vnpay: "正在连接 VNPay...",
    btn_free_trial_3d: "快速 3 天免费试用",
    btn_close: "关闭",
    payment_success_title: "支付成功！🎉",
    payment_success_desc: "您的账户已成功升级为 VIP Premium。所有专属特权已激活！",
    payment_failed_title: "支付失败",
    payment_failed_desc: "VNPay 支付交易失败或已取消。请重试。",
    btn_back_to_home: "返回首页",
    payment_order_code: "订单 ID：",
    payment_history_title: "VNPay 支付交易历史",
    payment_history_no_orders: "暂无支付交易历史。",
    payment_col_order_id: "订单 ID",
    payment_col_package: "套餐",
    payment_col_amount: "金额",
    payment_col_status: "状态",
    payment_col_date: "创建日期",
    payment_status_success: "成功",
    payment_status_pending: "处理中",
    payment_status_expired: "已过期",
    payment_status_failed: "失败",
    profile_vip_active_badge: "VIP 特权已激活",
    profile_btn_upgrade_vip: "升级 VIP Premium",
    profile_tab_premium: "VIP Premium",
    chart_vip_feature_tag: "VIP 特权",
    chart_lock_title: "解锁 7 天分析图表",
    chart_lock_desc: "升级 VIP Premium 查看每周深度学习分析！",
    chart_lock_upgrade_btn: "立即升级 Premium",

    // Study Drive i18n
    drive_title: "学习云盘",
    drive_subtitle: "云端学习文档存储",
    drive_back_dashboard: "返回仪表板",
    drive_search_placeholder: "搜索学习文档...",
    drive_create_folder: "新建文件夹",
    drive_upload_file: "上传文件",
    upload_popup_title: "上传进度",
    upload_popup_warning: "上传过程中请勿关闭或切换页面。",
    uploading_file: "正在上传",
    upload_completed: "上传完成",
    upload_failed: "上传失败",
    upload_file_count: "文件 {current}/{total}",
    toast_success_title: "成功",
    drive_upload_success_title: "文件上传成功",
    drive_upload_success_desc: "已成功上传 {count} 个文件",
    error_file_size_exceeded: "文件“{name}”超过 200 MB 大小限制。",
    error_quota_exceeded: "存储空间不足！(可用：{available}，需要：{required})",
    drive_tab_mydrive: "我的云盘",
    drive_tab_favorites: "收藏夹",
    drive_tab_trash: "回收站",
    drive_storage_header: "账户存储",
    drive_used: "已用",
    drive_user_quota: "用户配额：1 GB",
    drive_max_file_size: "单文件上限：200 MB",
    drive_search_results_for: "搜索结果：",
    drive_favorites_title: "收藏的文档",
    drive_trash_title: "回收站",
    drive_grid_view: "网格视图",
    drive_list_view: "列表视图",
    drive_empty_title: "暂无文档",
    drive_empty_desc: "拖拽文件到此处或点击“上传文件”存储您的学习文档。",
    drive_empty_btn: "上传第一个文件",
    drive_col_name: "名称",
    drive_col_size: "大小",
    drive_col_date: "上传日期",
    drive_col_actions: "操作",
    drive_folder: "文件夹",
    drive_restore: "恢复",
    drive_perm_delete: "永久删除",
    drive_download: "下载",
    drive_rename: "重命名",
    drive_delete: "移至回收站",
    drive_modal_create_folder: "新建文件夹",
    drive_modal_folder_placeholder: "文件夹名称（如：高等数学）...",
    drive_btn_cancel: "取消",
    drive_btn_save: "保存",
    drive_modal_rename: "重命名",
    drive_preview_unsupported: "不支持直接预览此文件格式",
    drive_preview_download_btn: "下载到设备查看",
    nav_drive: "文档",
    nav_drive_title: "学习文档云盘",
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    if (saved && (saved === 'vi' || saved === 'en' || saved === 'zh')) {
      return saved;
    }
    // Default to English
    return 'en';
  });

  useEffect(() => {
    const handleCustomLangChange = (e) => {
      const newLang = e.detail || localStorage.getItem('language');
      if (newLang && (newLang === 'vi' || newLang === 'en' || newLang === 'zh')) {
        setLanguage(newLang);
      }
    };
    window.addEventListener('language-change', handleCustomLangChange);
    return () => window.removeEventListener('language-change', handleCustomLangChange);
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
    
    // SEO Dynamic Update
    document.documentElement.lang = language;
    
    let title = "Study XP Tracker - Hệ thống theo dõi học tập và thăng cấp XP";
    let description = "Study XP Tracker giúp bạn theo dõi thời gian học tập, tích lũy điểm kinh nghiệm (XP), thăng cấp và duy trì chuỗi học tập hàng ngày. Học tập hiệu quả hơn cùng bạn bè.";
    
    if (language === 'en') {
      title = "Study XP Tracker - Level up your study routine";
      description = "Study XP Tracker helps you track your study time, accumulate Experience Points (XP), level up, and maintain daily study streaks. Study better with friends.";
    } else if (language === 'zh') {
      title = "Study XP Tracker - 追踪学习进度，提升等级";
      description = "Study XP Tracker 帮助您跟踪学习时间，累积经验值（XP），提升等级，并保持每日学习习惯。与朋友一起更高效地学习。";
    }
    
    document.title = title;
    
    // Update meta title tag
    let metaTitle = document.querySelector('meta[name="title"]');
    if (metaTitle) metaTitle.setAttribute('content', title);
    
    // Update description tag
    let metaDesc = document.querySelector('meta[name="description"]');
    if (!metaDesc) {
      metaDesc = document.createElement('meta');
      metaDesc.setAttribute('name', 'description');
      document.head.appendChild(metaDesc);
    }
    metaDesc.setAttribute('content', description);
    
    // Update Open Graph (og:) tags
    let ogTitle = document.querySelector('meta[property="og:title"]');
    if (ogTitle) ogTitle.setAttribute('content', title);
    
    let ogDesc = document.querySelector('meta[property="og:description"]');
    if (ogDesc) ogDesc.setAttribute('content', description);
    
    let ogLocale = document.querySelector('meta[property="og:locale"]');
    if (ogLocale) {
      const locales = { vi: 'vi_VN', en: 'en_US', zh: 'zh_CN' };
      ogLocale.setAttribute('content', locales[language] || 'vi_VN');
    }
    
    // Update Twitter tags
    let twitterTitle = document.querySelector('meta[name="twitter:title"]');
    if (twitterTitle) twitterTitle.setAttribute('content', title);
    
    let twitterDesc = document.querySelector('meta[name="twitter:description"]');
    if (twitterDesc) twitterDesc.setAttribute('content', description);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
